/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API Root & Navigation Index
         * @description Returns basic API service metadata and documentation links.
         */
        get: operations["root_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/cache/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Flush Analytics Cache
         * @description Invalidates and purges all active items from the in-memory analytics cache.
         */
        post: operations["purge_analytics_cache_api_analytics_cache_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/cache/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Analytics Cache Telemetry
         * @description Returns real-time in-memory TTL cache telemetry: hits, misses, bypasses, evictions, and hit ratio.
         */
        get: operations["get_cache_telemetry_api_analytics_cache_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio Macro Overview KPIs
         * @description Returns high-level customer retention, aggregate spend, repeat purchase rate, and total revenue-at-risk exposure across the portfolio.
         */
        get: operations["get_portfolio_overview_api_analytics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Customer Cohort Retention Analysis
         * @description Returns month-by-month customer cohort survival rates (M+0 to M+12) tracking customer retention decay curves based on first purchase acquisition cohorts.
         */
        get: operations["get_cohort_retention_api_analytics_retention_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/revenue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revenue Trends Time-Series
         * @description Returns chronological gross merchandise value (GMV), order volume, AOV, freight expenses, and late delivery rate time-series trends grouped by interval.
         */
        get: operations["get_revenue_trends_api_analytics_revenue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/revenue-at-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revenue-at-Risk & Retention Action Matrix
         * @description Detailed financial breakdown of churn exposure grouped by risk tier and prioritized retention action groups, including a top at-risk customer preview.
         */
        get: operations["get_revenue_at_risk_overview_api_analytics_revenue_at_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/rfm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * RFM Segmentation Breakdown (Alias)
         * @description Convenience alias returning RFM segment distributions.
         */
        get: operations["get_rfm_overview_api_analytics_rfm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * RFM Segmentation Breakdown
         * @description Returns portfolio customer distribution across named RFM segments (Champions, Loyal Customers, Potential Loyalists, New, At Risk, Lost, Others).
         */
        get: operations["get_segments_overview_api_analytics_segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Authentication Identity
         * @description Returns identity and scope details for the currently authenticated caller.
         */
        get: operations["get_auth_identity_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Bearer Access Token
         * @description Issues an HMAC-SHA256 signed JWT Bearer token valid for API access.
         */
        post: operations["generate_token_api_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Customers (Paginated & Filtered)
         * @description Query customers with optional filtering by RFM segment, churn risk tier, retention priority, Brazilian state, spend range, or customer identifier search.
         */
        get: operations["list_customers_api_customers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/at-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * At-Risk Customer Retention Queue
         * @description High-priority queue of customers with elevated churn probability, ordered by expected monetary revenue at risk (descending).
         */
        get: operations["get_at_risk_customers_api_customers_at_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Customers for CRM Campaigns (Streaming CSV)
         * @description Streams a formatted CSV export of customers with lifetime spend, churn risk tier, retention priority, and recommended action based on applied filters.
         */
        get: operations["export_customers_csv_api_customers_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Customer Segments Breakdown (Convenience Alias)
         * @description Returns aggregate RFM customer segmentation summary.
         */
        get: operations["get_customer_segments_alias_api_customers_segments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_unique_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Customer 360 Profile
         * @description Returns complete customer profile: order history, basket metrics, fulfillment friction, review ratings, RFM scores, and ML churn prediction.
         */
        get: operations["get_customer_detail_api_customers__customer_unique_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_unique_id}/churn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Customer Churn Prediction
         * @description Returns the churn probability, risk tier, revenue at risk, and retention priority.
         */
        get: operations["get_customer_churn_api_customers__customer_unique_id__churn_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_unique_id}/rfm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Customer RFM Scorecard
         * @description Returns the RFM quintile scores, composite score, and segment for a customer.
         */
        get: operations["get_customer_rfm_api_customers__customer_unique_id__rfm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API system health check
         * @description Check API service status, environment details, and live PostgreSQL connectivity.
         */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Product Catalog (Paginated)
         * @description Returns a paginated list of catalog products with sales volume, total revenue, average unit price, customer review ratings, and package specifications.
         */
        get: operations["list_products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product Categories Breakdown
         * @description Returns aggregate product sales performance and revenue contribution broken down across distinct marketplace merchandise categories.
         */
        get: operations["get_categories_overview_api_products_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product 360 Scorecard
         * @description Returns performance metrics, sales velocity, customer review ratings, and physical dimensions for an individual catalog product.
         */
        get: operations["get_product_detail_api_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sellers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Marketplace Sellers (Paginated)
         * @description Returns a paginated list of marketplace sellers with gross merchandise value, fulfilled orders, delivery delay averages, late delivery rates, and review ratings.
         */
        get: operations["list_sellers_api_sellers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sellers/{seller_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Seller 360 Profile
         * @description Returns complete performance profile for a specific marketplace seller, including top product categories, delivery delay rates, and review ratings.
         */
        get: operations["get_seller_detail_api_sellers__seller_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System health check
         * @description Check API service status, environment details, and live PostgreSQL connectivity.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CategoryListResponse
         * @description Aggregate category list response.
         */
        CategoryListResponse: {
            /**
             * Categories
             * @description Category performance summaries
             */
            categories: components["schemas"]["CategorySummary"][];
            /**
             * Total Categories
             * @description Number of distinct product categories
             */
            total_categories: number;
        };
        /**
         * CategorySummary
         * @description Macro performance metrics for a product category.
         */
        CategorySummary: {
            /**
             * Avg Price
             * @description Average item selling price in BRL
             */
            avg_price: number;
            /**
             * Avg Review Score
             * @description Average category review score
             */
            avg_review_score?: number | null;
            /**
             * Category
             * @description English category slug or name
             */
            category: string;
            /**
             * Category Pt
             * @description Original Portuguese category name
             */
            category_pt?: string | null;
            /**
             * Total Products
             * @description Total distinct product catalog items in category
             */
            total_products: number;
            /**
             * Total Revenue
             * @description Gross category revenue in BRL
             */
            total_revenue: number;
            /**
             * Total Units Sold
             * @description Total units sold in category
             */
            total_units_sold: number;
        };
        /**
         * ChurnPrediction
         * @description Customer-level churn probability, risk tier, and expected revenue at risk.
         */
        ChurnPrediction: {
            /**
             * Churn Probability
             * @description Predicted probability of churn P(Churn)
             */
            churn_probability: number;
            /**
             * Customer Unique Id
             * @description Unique returning customer identifier
             */
            customer_unique_id: string;
            /**
             * Is Churned
             * @description Observed ground truth inactivity label (1=churned, 0=active)
             */
            is_churned: number;
            /**
             * Monetary Value
             * @description Customer lifetime spend in BRL (R$)
             */
            monetary_value: number;
            /**
             * Predicted At
             * @description Timestamp of inference generation
             */
            predicted_at?: string | null;
            /**
             * Retention Priority
             * @description Decision matrix retention action group
             */
            retention_priority: string;
            /**
             * Revenue At Risk
             * @description Expected monetary revenue at risk P(Churn) * monetary_value
             */
            revenue_at_risk: number;
            /**
             * Risk Tier
             * @description Categorical risk tier: High (>=0.70), Medium (0.30-0.70), Low (<0.30)
             */
            risk_tier: string;
        };
        /**
         * CohortRetentionPoint
         * @description Customer cohort retention rates over month-by-month survival lifecycle.
         */
        CohortRetentionPoint: {
            /**
             * Cohort Month
             * @description Acquisition cohort month in YYYY-MM format
             */
            cohort_month: string;
            /**
             * Cohort Size
             * @description Total distinct customers acquired in this cohort month
             */
            cohort_size: number;
            /**
             * Retention Rates
             * @description Retention survival rates indexed by month offset (e.g. {'m0': 100.0, 'm1': 4.2})
             */
            retention_rates: {
                [key: string]: number;
            };
        };
        /**
         * CustomerBasketMetrics
         * @description Customer basket diversity and volume metrics.
         */
        CustomerBasketMetrics: {
            /**
             * Avg Items Per Order
             * @description Average items per order
             * @default 0
             */
            avg_items_per_order: number;
            /**
             * Lifetime Items
             * @description Total units/items purchased across all orders
             * @default 0
             */
            lifetime_items: number;
            /**
             * Total Unique Products Purchased
             * @description Distinct product IDs purchased
             * @default 0
             */
            total_unique_products_purchased: number;
            /**
             * Total Unique Sellers Contacted
             * @description Distinct marketplace sellers purchased from
             * @default 0
             */
            total_unique_sellers_contacted: number;
        };
        /**
         * CustomerDetail
         * @description Comprehensive 360-degree customer intelligence profile.
         */
        CustomerDetail: {
            /**
             * Avg Order Value
             * @description Average spend per order in BRL
             */
            avg_order_value: number;
            /** @description Basket volume and product diversity */
            basket: components["schemas"]["CustomerBasketMetrics"];
            /** @description Churn risk score and revenue at risk */
            churn?: components["schemas"]["ChurnPrediction"] | null;
            /**
             * City
             * @description Customer primary city
             */
            city?: string | null;
            /**
             * Customer Lifespan Days
             * @description Days between first and latest purchase
             */
            customer_lifespan_days?: number | null;
            /**
             * Customer Unique Id
             * @description Unique returning customer identifier
             */
            customer_unique_id: string;
            /**
             * First Purchased At
             * @description Timestamp of first order
             */
            first_purchased_at?: string | null;
            /** @description Delivery speed and delay friction */
            fulfillment: components["schemas"]["CustomerFulfillmentMetrics"];
            /**
             * Is Repeat Buyer
             * @description 1 if >=2 orders, else 0
             */
            is_repeat_buyer: number;
            /**
             * Latest Purchased At
             * @description Timestamp of latest order
             */
            latest_purchased_at?: string | null;
            /**
             * Lifetime Freight Spend
             * @description Spend on shipping/freight in BRL
             * @default 0
             */
            lifetime_freight_spend: number;
            /**
             * Lifetime Orders
             * @description Total completed orders
             */
            lifetime_orders: number;
            /**
             * Lifetime Product Spend
             * @description Spend on product items in BRL
             * @default 0
             */
            lifetime_product_spend: number;
            /**
             * Lifetime Spend
             * @description Total gross spend in BRL
             */
            lifetime_spend: number;
            /**
             * Recency Days
             * @description Days since latest purchase
             */
            recency_days?: number | null;
            /** @description Review ratings and sentiment */
            reviews: components["schemas"]["CustomerReviewMetrics"];
            /** @description Complete RFM quintile scores and segment */
            rfm?: components["schemas"]["RFMScorecard"] | null;
            /**
             * State
             * @description Customer primary state abbreviation
             */
            state?: string | null;
            /**
             * Zip Prefix
             * @description Five-digit zip code prefix
             */
            zip_prefix?: string | null;
        };
        /**
         * CustomerFulfillmentMetrics
         * @description Fulfillment speed, delivery delays, and shipping friction metrics.
         */
        CustomerFulfillmentMetrics: {
            /**
             * Avg Delivery Delay Days
             * @description Average delivery delay in days vs estimated date
             */
            avg_delivery_delay_days?: number | null;
            /**
             * Has Late Delivery
             * @description 1 if customer experienced at least one late delivery, else 0
             * @default 0
             */
            has_late_delivery: number;
            /**
             * Late Order Ratio
             * @description Proportion of orders delivered late
             * @default 0
             */
            late_order_ratio: number;
            /**
             * Late Orders Count
             * @description Number of orders delivered past estimated date
             * @default 0
             */
            late_orders_count: number;
            /**
             * Max Delivery Delay Days
             * @description Maximum delivery delay experienced in days
             */
            max_delivery_delay_days?: number | null;
        };
        /**
         * CustomerListResponse
         * @description Paginated list of customer summaries with query metadata.
         */
        CustomerListResponse: {
            /**
             * Items
             * @description List of customers for the current page
             */
            items: components["schemas"]["CustomerSummary"][];
            /** @description Pagination metadata */
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * CustomerReviewMetrics
         * @description Customer feedback and sentiment satisfaction metrics.
         */
        CustomerReviewMetrics: {
            /**
             * Avg Review Score
             * @description Average review rating (1 to 5)
             */
            avg_review_score?: number | null;
            /**
             * Has Negative Review
             * @description 1 if customer gave at least one negative review, else 0
             * @default 0
             */
            has_negative_review: number;
            /**
             * Negative Review Ratio
             * @description Ratio of negative reviews to total submitted
             * @default 0
             */
            negative_review_ratio: number;
            /**
             * Negative Reviews Count
             * @description Count of negative reviews (rating <= 2)
             * @default 0
             */
            negative_reviews_count: number;
            /**
             * Positive Reviews Count
             * @description Count of positive reviews (rating >= 4)
             * @default 0
             */
            positive_reviews_count: number;
            /**
             * Total Reviews Submitted
             * @description Total order reviews submitted
             * @default 0
             */
            total_reviews_submitted: number;
        };
        /**
         * CustomerSummary
         * @description Condensed customer summary for table views and paginated listings.
         */
        CustomerSummary: {
            /**
             * Avg Order Value
             * @description Average spend per order in BRL
             */
            avg_order_value: number;
            /**
             * Churn Probability
             * @description Predicted churn probability P(Churn)
             */
            churn_probability?: number | null;
            /**
             * City
             * @description Customer primary city
             */
            city?: string | null;
            /**
             * Customer Lifespan Days
             * @description Days between first and latest purchase
             */
            customer_lifespan_days?: number | null;
            /**
             * Customer Unique Id
             * @description Unique returning customer identifier
             */
            customer_unique_id: string;
            /**
             * First Purchased At
             * @description Timestamp of first order
             */
            first_purchased_at?: string | null;
            /**
             * Is Repeat Buyer
             * @description 1 if >=2 orders, else 0
             */
            is_repeat_buyer: number;
            /**
             * Latest Purchased At
             * @description Timestamp of latest order
             */
            latest_purchased_at?: string | null;
            /**
             * Lifetime Orders
             * @description Total completed orders
             */
            lifetime_orders: number;
            /**
             * Lifetime Spend
             * @description Total gross spend in BRL
             */
            lifetime_spend: number;
            /**
             * Recency Days
             * @description Days since latest purchase
             */
            recency_days?: number | null;
            /**
             * Retention Priority
             * @description Prescribed retention priority action
             */
            retention_priority?: string | null;
            /**
             * Revenue At Risk
             * @description Monetary value at risk in BRL
             */
            revenue_at_risk?: number | null;
            /**
             * Risk Tier
             * @description Churn risk tier (High / Medium / Low)
             */
            risk_tier?: string | null;
            /**
             * Segment
             * @description Assigned RFM customer segment
             */
            segment?: string | null;
            /**
             * State
             * @description Customer primary state abbreviation
             */
            state?: string | null;
            /**
             * Zip Prefix
             * @description Five-digit zip code prefix
             */
            zip_prefix?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description System health check and diagnostic information.
         */
        HealthResponse: {
            /**
             * App Name
             * @description API service name
             */
            app_name: string;
            /**
             * Database
             * @description Database connectivity status and latency
             */
            database: Record<string, never>;
            /**
             * Status
             * @description Overall system status (ok / degraded)
             */
            status: string;
            /**
             * Timestamp
             * @description ISO 8601 UTC timestamp of check
             */
            timestamp: string;
            /**
             * Version
             * @description Current service release version
             */
            version: string;
        };
        /**
         * PaginationMeta
         * @description Pagination metadata included in paginated list responses.
         */
        PaginationMeta: {
            /**
             * Has Next
             * @description Whether there is a next page
             */
            has_next: boolean;
            /**
             * Has Prev
             * @description Whether there is a previous page
             */
            has_prev: boolean;
            /**
             * Page
             * @description Current page number (1-indexed)
             */
            page: number;
            /**
             * Page Size
             * @description Number of items per page
             */
            page_size: number;
            /**
             * Total Items
             * @description Total matching items across all pages
             */
            total_items: number;
            /**
             * Total Pages
             * @description Total number of pages
             */
            total_pages: number;
        };
        /**
         * PortfolioOverview
         * @description Macro-level portfolio retention and customer intelligence KPIs.
         */
        PortfolioOverview: {
            /**
             * Avg Churn Probability
             * @description Portfolio mean customer churn probability
             */
            avg_churn_probability: number;
            /**
             * Avg Order Value
             * @description Portfolio-wide average order value in BRL
             */
            avg_order_value: number;
            /**
             * High Risk Customers Count
             * @description Total customers with P(Churn) >= 0.70
             */
            high_risk_customers_count: number;
            /**
             * High Risk Percentage
             * @description Percentage of customers categorized as High Risk
             */
            high_risk_percentage: number;
            /**
             * Portfolio Revenue At Risk
             * @description Total expected monetary revenue at risk in BRL
             */
            portfolio_revenue_at_risk: number;
            /**
             * Portfolio Risk Percentage
             * @description Proportion of total revenue currently at risk
             */
            portfolio_risk_percentage: number;
            /**
             * Repeat Buyer Rate
             * @description Percentage of repeat customers (lifetime orders >= 2)
             */
            repeat_buyer_rate: number;
            /**
             * Total Customers
             * @description Total unique customers in portfolio
             */
            total_customers: number;
            /**
             * Total Orders
             * @description Total completed delivered orders
             */
            total_orders: number;
            /**
             * Total Revenue
             * @description Total historical portfolio revenue in BRL
             */
            total_revenue: number;
            /**
             * Vip Retention Revenue At Risk
             * @description Revenue at risk in Priority 1 (VIP Retention)
             */
            vip_retention_revenue_at_risk: number;
        };
        /**
         * ProductListResponse
         * @description Paginated list envelope for product catalog items.
         */
        ProductListResponse: {
            /**
             * Items
             * @description Products matching query filters
             */
            items: components["schemas"]["ProductSummary"][];
            /** @description Pagination metadata */
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * ProductSummary
         * @description Performance summary and physical dimensions for a product catalog item.
         */
        ProductSummary: {
            /**
             * Avg Review Score
             * @description Average customer review rating (1.0 - 5.0)
             */
            avg_review_score?: number | null;
            /**
             * Avg Unit Price
             * @description Average retail price in BRL
             * @default 0
             */
            avg_unit_price: number;
            /**
             * Category Name En
             * @description English category name translation
             */
            category_name_en?: string | null;
            /**
             * Category Name Pt
             * @description Original Portuguese category name
             */
            category_name_pt?: string | null;
            /**
             * Product Height Cm
             * @description Product package height in cm
             */
            product_height_cm?: number | null;
            /**
             * Product Id
             * @description Unique product identifier (UUID hex)
             */
            product_id: string;
            /**
             * Product Length Cm
             * @description Product package length in cm
             */
            product_length_cm?: number | null;
            /**
             * Product Photos Qty
             * @description Number of product gallery photos published
             */
            product_photos_qty?: number | null;
            /**
             * Product Weight G
             * @description Product weight in grams
             */
            product_weight_g?: number | null;
            /**
             * Product Width Cm
             * @description Product package width in cm
             */
            product_width_cm?: number | null;
            /**
             * Total Orders Count
             * @description Distinct delivered orders containing this product
             * @default 0
             */
            total_orders_count: number;
            /**
             * Total Revenue
             * @description Gross revenue generated (price + freight) in BRL
             * @default 0
             */
            total_revenue: number;
            /**
             * Total Units Sold
             * @description Total units sold across all delivered orders
             * @default 0
             */
            total_units_sold: number;
        };
        /**
         * RFMScorecard
         * @description Customer-level RFM scorecard and assigned segment.
         */
        RFMScorecard: {
            /**
             * Computed At
             * @description Timestamp when scores were calculated
             */
            computed_at?: string | null;
            /**
             * Customer Unique Id
             * @description Unique returning customer identifier
             */
            customer_unique_id: string;
            /**
             * F Score
             * @description Frequency score (1=one order, 5=repeat high-frequency)
             */
            f_score: number;
            /**
             * Frequency
             * @description Total completed lifetime delivered orders
             */
            frequency: number;
            /**
             * M Score
             * @description Monetary score (1=lowest spend, 5=highest spend)
             */
            m_score: number;
            /**
             * Monetary
             * @description Total lifetime gross spend in BRL (R$)
             */
            monetary: number;
            /**
             * R Score
             * @description Recency score (1=least recent, 5=most recent)
             */
            r_score: number;
            /**
             * Recency Days
             * @description Days elapsed between customer's latest purchase and cutoff
             */
            recency_days: number;
            /**
             * Rfm Label
             * @description Concatenated quintile label, e.g. '515'
             */
            rfm_label: string;
            /**
             * Rfm Score
             * @description Composite mean of (R, F, M) scores
             */
            rfm_score: number;
            /**
             * Segment
             * @description Named customer intelligence segment
             */
            segment: string;
        };
        /**
         * RetentionAnalyticsResponse
         * @description Comprehensive cohort retention curves across acquisition months.
         */
        RetentionAnalyticsResponse: {
            /**
             * Cohorts
             * @description Cohort retention survival matrices
             */
            cohorts: components["schemas"]["CohortRetentionPoint"][];
            /**
             * Total Cohorts
             * @description Total customer acquisition cohorts analyzed
             */
            total_cohorts: number;
        };
        /**
         * RetentionPrioritySummary
         * @description Portfolio breakdown aggregated by retention priority action.
         */
        RetentionPrioritySummary: {
            /**
             * Customer Count
             * @description Number of customers assigned to this priority
             */
            customer_count: number;
            /**
             * Percentage
             * @description Percentage of customer portfolio
             */
            percentage: number;
            /**
             * Retention Priority
             * @description Strategic retention priority action
             */
            retention_priority: string;
            /**
             * Total Revenue At Risk
             * @description Total revenue at risk tied to this action group
             */
            total_revenue_at_risk: number;
        };
        /**
         * RevenueAnalyticsResponse
         * @description Time-series revenue trends response with summary metadata.
         */
        RevenueAnalyticsResponse: {
            /**
             * Interval
             * @description Granularity interval: 'month', 'week', or 'day'
             */
            interval: string;
            /**
             * Total Periods
             * @description Number of historical time periods returned
             */
            total_periods: number;
            /**
             * Trends
             * @description Ordered chronological trend data points
             */
            trends: components["schemas"]["RevenueTrendPoint"][];
        };
        /**
         * RevenueAtRiskOverview
         * @description Detailed financial breakdown of churn exposure and retention priority groups.
         */
        RevenueAtRiskOverview: {
            /**
             * By Retention Priority
             * @description Actionable retention priority segments
             */
            by_retention_priority: components["schemas"]["RetentionPrioritySummary"][];
            /**
             * By Risk Tier
             * @description Risk distribution across High, Medium, Low
             */
            by_risk_tier: components["schemas"]["RiskTierSummary"][];
            /**
             * Portfolio Risk Percentage
             * @description Revenue at risk as percentage of total revenue
             */
            portfolio_risk_percentage: number;
            /**
             * Top At Risk Preview
             * @description Top high-value customers at risk
             */
            top_at_risk_preview?: components["schemas"]["CustomerSummary"][] | null;
            /**
             * Total Historical Spend
             * @description Total lifetime historical spend in BRL
             */
            total_historical_spend: number;
            /**
             * Total Revenue At Risk
             * @description Total expected monetary revenue at risk in BRL
             */
            total_revenue_at_risk: number;
        };
        /**
         * RevenueTrendPoint
         * @description Historical time-series revenue and fulfillment data point.
         */
        RevenueTrendPoint: {
            /**
             * Avg Order Value
             * @description Average order value in BRL
             */
            avg_order_value: number;
            /**
             * Delivered Count
             * @description Orders successfully delivered in this period
             */
            delivered_count: number;
            /**
             * Gmv
             * @description Gross merchandise value (product + freight) in BRL
             */
            gmv: number;
            /**
             * Late Order Rate
             * @description Percentage of orders delivered past estimated date
             */
            late_order_rate: number;
            /**
             * Orders Count
             * @description Total orders placed in this period
             */
            orders_count: number;
            /**
             * Period
             * @description Time period label (e.g. '2017-01' or '2017-W14')
             */
            period: string;
            /**
             * Total Freight
             * @description Total shipping freight charges in BRL
             */
            total_freight: number;
        };
        /**
         * RiskTierSummary
         * @description Portfolio breakdown aggregated by churn risk tier.
         */
        RiskTierSummary: {
            /**
             * Avg Churn Probability
             * @description Mean predicted churn probability
             */
            avg_churn_probability: number;
            /**
             * Customer Count
             * @description Number of customers in this risk tier
             */
            customer_count: number;
            /**
             * Percentage
             * @description Percentage of customer portfolio
             */
            percentage: number;
            /**
             * Risk Tier
             * @description Risk tier: High, Medium, Low
             */
            risk_tier: string;
            /**
             * Total Revenue At Risk
             * @description Sum of expected revenue at risk in BRL
             */
            total_revenue_at_risk: number;
        };
        /**
         * SegmentDistribution
         * @description Aggregate portfolio summary for a specific RFM customer segment.
         */
        SegmentDistribution: {
            /**
             * Avg Frequency
             * @description Average number of lifetime orders
             */
            avg_frequency: number;
            /**
             * Avg Recency Days
             * @description Average days since latest purchase
             */
            avg_recency_days: number;
            /**
             * Avg Spend
             * @description Average monetary spend per customer in BRL
             */
            avg_spend: number;
            /**
             * Customer Count
             * @description Number of customers in this segment
             */
            customer_count: number;
            /**
             * Percentage
             * @description Percentage of total customer base
             */
            percentage: number;
            /**
             * Segment
             * @description Customer segment name
             */
            segment: string;
            /**
             * Total Spend
             * @description Total lifetime spend generated by this segment in BRL
             */
            total_spend: number;
        };
        /**
         * SegmentsOverview
         * @description Distribution of customer base across RFM behavioral segments.
         */
        SegmentsOverview: {
            /**
             * Segments
             * @description Per-segment customer counts, spend, and averages
             */
            segments: components["schemas"]["SegmentDistribution"][];
            /**
             * Total Customers
             * @description Total customers analyzed
             */
            total_customers: number;
        };
        /**
         * SellerDetail
         * @description Detailed 360-degree seller intelligence profile.
         */
        SellerDetail: {
            /**
             * Avg Delivery Delay Days
             * @description Mean delivery delay in days relative to estimated delivery date
             */
            avg_delivery_delay_days?: number | null;
            /**
             * Avg Item Value
             * @description Average order line-item value in BRL
             * @default 0
             */
            avg_item_value: number;
            /**
             * Avg Review Score
             * @description Mean customer review rating (1.0 - 5.0)
             */
            avg_review_score?: number | null;
            /**
             * City
             * @description Seller city
             */
            city?: string | null;
            /**
             * Late Delivery Rate
             * @description Percentage of orders delivered past estimated date
             * @default 0
             */
            late_delivery_rate: number;
            /**
             * Positive Reviews Rate
             * @description Percentage of customer reviews rated 4 or 5 stars
             * @default 0
             */
            positive_reviews_rate: number;
            /**
             * Seller Id
             * @description Unique seller identifier (UUID hex)
             */
            seller_id: string;
            /**
             * State
             * @description Two-letter Brazilian state abbreviation
             */
            state?: string | null;
            /**
             * Top Categories
             * @description Top product categories sold by this seller
             */
            top_categories?: string[];
            /**
             * Total Items Sold
             * @description Total units/line-items sold across orders
             * @default 0
             */
            total_items_sold: number;
            /**
             * Total Orders Fulfilled
             * @description Count of distinct delivered orders fulfilled
             * @default 0
             */
            total_orders_fulfilled: number;
            /**
             * Total Revenue
             * @description Gross revenue generated (items + freight) in BRL
             * @default 0
             */
            total_revenue: number;
            /**
             * Total Unique Products
             * @description Distinct product catalog items sold
             * @default 0
             */
            total_unique_products: number;
            /**
             * Zip Prefix
             * @description Seller 5-digit zip code prefix
             */
            zip_prefix?: string | null;
        };
        /**
         * SellerListResponse
         * @description Paginated list envelope for seller summaries.
         */
        SellerListResponse: {
            /**
             * Items
             * @description Sellers matching the filter criteria
             */
            items: components["schemas"]["SellerSummary"][];
            /** @description Pagination metadata */
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * SellerSummary
         * @description Aggregate performance and fulfillment scorecard for a marketplace seller.
         */
        SellerSummary: {
            /**
             * Avg Delivery Delay Days
             * @description Mean delivery delay in days relative to estimated delivery date
             */
            avg_delivery_delay_days?: number | null;
            /**
             * Avg Item Value
             * @description Average order line-item value in BRL
             * @default 0
             */
            avg_item_value: number;
            /**
             * Avg Review Score
             * @description Mean customer review rating (1.0 - 5.0)
             */
            avg_review_score?: number | null;
            /**
             * City
             * @description Seller city
             */
            city?: string | null;
            /**
             * Late Delivery Rate
             * @description Percentage of orders delivered past estimated date
             * @default 0
             */
            late_delivery_rate: number;
            /**
             * Seller Id
             * @description Unique seller identifier (UUID hex)
             */
            seller_id: string;
            /**
             * State
             * @description Two-letter Brazilian state abbreviation
             */
            state?: string | null;
            /**
             * Total Items Sold
             * @description Total units/line-items sold across orders
             * @default 0
             */
            total_items_sold: number;
            /**
             * Total Orders Fulfilled
             * @description Count of distinct delivered orders fulfilled
             * @default 0
             */
            total_orders_fulfilled: number;
            /**
             * Total Revenue
             * @description Gross revenue generated (items + freight) in BRL
             * @default 0
             */
            total_revenue: number;
            /**
             * Total Unique Products
             * @description Distinct product catalog items sold
             * @default 0
             */
            total_unique_products: number;
            /**
             * Zip Prefix
             * @description Seller 5-digit zip code prefix
             */
            zip_prefix?: string | null;
        };
        /**
         * TokenRequest
         * @description Payload for requesting an access token.
         */
        TokenRequest: {
            /**
             * Api Key
             * @description API Key for credential verification.
             */
            api_key?: string | null;
            /**
             * Client Id
             * @description Client or application identifier.
             * @default mercury_client
             */
            client_id: string;
            /**
             * Expires In Minutes
             * @description Desired token lifetime in minutes (5 to 1440).
             * @default 60
             */
            expires_in_minutes: number | null;
        };
        /**
         * TokenResponse
         * @description Token response containing signed JWT and token parameters.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description HMAC-SHA256 signed JWT access token.
             */
            access_token: string;
            /**
             * Expires In
             * @description Token lifespan in seconds.
             */
            expires_in: number;
            /**
             * Token Type
             * @description Token type, always 'bearer'.
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UserIdentity
         * @description Authenticated user/client identity representation.
         */
        UserIdentity: {
            /**
             * Auth Type
             * @description Authentication mechanism ('api_key', 'bearer', 'dev_bypass').
             */
            auth_type: string;
            /**
             * Authenticated
             * @description Authentication status flag.
             */
            authenticated: boolean;
            /**
             * Roles
             * @description Assigned role scopes.
             */
            roles?: string[];
            /**
             * User
             * @description Identifier of the authenticated subject.
             */
            user: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root_index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    purge_analytics_cache_api_analytics_cache_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_cache_telemetry_api_analytics_cache_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_portfolio_overview_api_analytics_overview_get: {
        parameters: {
            query?: {
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cohort_retention_api_analytics_retention_get: {
        parameters: {
            query?: {
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetentionAnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_revenue_trends_api_analytics_revenue_get: {
        parameters: {
            query?: {
                /** @description Grouping interval: month, week, or day */
                interval?: string;
                /** @description Start date filter (YYYY-MM-DD) */
                start_date?: string | null;
                /** @description End date filter (YYYY-MM-DD) */
                end_date?: string | null;
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevenueAnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_revenue_at_risk_overview_api_analytics_revenue_at_risk_get: {
        parameters: {
            query?: {
                /** @description Include top 5 at-risk customer preview */
                include_preview?: boolean;
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevenueAtRiskOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rfm_overview_api_analytics_rfm_get: {
        parameters: {
            query?: {
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_segments_overview_api_analytics_segments_get: {
        parameters: {
            query?: {
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_auth_identity_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserIdentity"];
                };
            };
        };
    };
    generate_token_api_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_customers_api_customers_get: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Items per page (max 100) */
                page_size?: number;
                /** @description Filter by RFM segment */
                segment?: string | null;
                /** @description Filter by Churn Risk Tier (High, Medium, Low) */
                risk_tier?: string | null;
                /** @description Filter by Retention Priority Action */
                retention_priority?: string | null;
                /** @description Filter by 2-letter state abbreviation (e.g. SP, RJ) */
                state?: string | null;
                /** @description Minimum lifetime spend in BRL */
                min_spend?: number | null;
                /** @description Maximum lifetime spend in BRL */
                max_spend?: number | null;
                /** @description Search by customer_unique_id */
                search?: string | null;
                /** @description Sort field: lifetime_spend, recency_days, lifetime_orders, avg_order_value, revenue_at_risk, churn_probability */
                sort_by?: string;
                /** @description Sort order direction: asc or desc */
                sort_order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_at_risk_customers_api_customers_at_risk_get: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Items per page (max 100) */
                page_size?: number;
                /** @description Filter risk tier (High or Medium) */
                risk_tier?: string | null;
                /** @description Filter by retention priority action */
                retention_priority?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_customers_csv_api_customers_export_get: {
        parameters: {
            query?: {
                /** @description Filter by RFM segment */
                segment?: string | null;
                /** @description Filter by churn risk tier (High, Medium, Low) */
                risk_tier?: string | null;
                /** @description Filter by retention priority action */
                retention_priority?: string | null;
                /** @description Filter by 2-letter state abbreviation */
                state?: string | null;
                /** @description Minimum lifetime spend in BRL */
                min_spend?: number | null;
                /** @description Maximum lifetime spend in BRL */
                max_spend?: number | null;
                /** @description Export format (csv) */
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_segments_alias_api_customers_segments_get: {
        parameters: {
            query?: {
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentsOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_detail_api_customers__customer_unique_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_unique_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_churn_api_customers__customer_unique_id__churn_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_unique_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChurnPrediction"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_rfm_api_customers__customer_unique_id__rfm_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_unique_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RFMScorecard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_products_api_products_get: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Items per page (max 100) */
                page_size?: number;
                /** @description Filter by category name (English or Portuguese) */
                category?: string | null;
                /** @description Sort field: total_revenue, total_units_sold, total_orders_count, avg_unit_price, avg_review_score */
                sort_by?: string;
                /** @description Sort order: asc or desc */
                sort_order?: string;
                /** @description Search by product_id or category */
                search?: string | null;
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_overview_api_products_categories_get: {
        parameters: {
            query?: {
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_detail_api_products__product_id__get: {
        parameters: {
            query?: {
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sellers_api_sellers_get: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Items per page (max 100) */
                page_size?: number;
                /** @description Filter by two-letter Brazilian state (e.g. SP, RJ) */
                state?: string | null;
                /** @description Sort field: total_revenue, total_orders_fulfilled, total_items_sold, avg_review_score, late_delivery_rate */
                sort_by?: string;
                /** @description Sort order: asc or desc */
                sort_order?: string;
                /** @description Search by seller_id or city */
                search?: string | null;
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellerListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_seller_detail_api_sellers__seller_id__get: {
        parameters: {
            query?: {
                /** @description Bypass in-memory cache and force live database query */
                bypass_cache?: boolean;
            };
            header?: never;
            path: {
                seller_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
