"""
backend/schemas/rfm.py
======================
Pydantic schemas for RFM scorecard, metrics, and customer segmentation distributions.
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional, Union
from pydantic import BaseModel, ConfigDict, Field


class RFMScorecard(BaseModel):
    """Customer-level RFM scorecard and assigned segment."""

    model_config = ConfigDict(from_attributes=True)

    customer_unique_id: str = Field(..., description="Unique returning customer identifier")
    recency_days: float = Field(..., description="Days elapsed between customer's latest purchase and cutoff")
    frequency: int = Field(..., description="Total completed lifetime delivered orders")
    monetary: float = Field(..., description="Total lifetime gross spend in BRL (R$)")
    r_score: int = Field(..., ge=1, le=5, description="Recency score (1=least recent, 5=most recent)")
    f_score: int = Field(..., ge=1, le=5, description="Frequency score (1=one order, 5=repeat high-frequency)")
    m_score: int = Field(..., ge=1, le=5, description="Monetary score (1=lowest spend, 5=highest spend)")
    rfm_score: float = Field(..., description="Composite mean of (R, F, M) scores")
    rfm_label: str = Field(..., description="Concatenated quintile label, e.g. '515'")
    segment: str = Field(..., description="Named customer intelligence segment")
    computed_at: Optional[Union[datetime, str]] = Field(None, description="Timestamp when scores were calculated")


class SegmentDistribution(BaseModel):
    """Aggregate portfolio summary for a specific RFM customer segment."""

    model_config = ConfigDict(from_attributes=True)

    segment: str = Field(..., description="Customer segment name")
    customer_count: int = Field(..., ge=0, description="Number of customers in this segment")
    percentage: float = Field(..., ge=0.0, le=100.0, description="Percentage of total customer base")
    total_spend: float = Field(..., ge=0.0, description="Total lifetime spend generated by this segment in BRL")
    avg_spend: float = Field(..., ge=0.0, description="Average monetary spend per customer in BRL")
    avg_recency_days: float = Field(..., ge=0.0, description="Average days since latest purchase")
    avg_frequency: float = Field(..., ge=0.0, description="Average number of lifetime orders")
